#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Derives the reference tables from the kit. Every cell is a fact about the tree
# — which files exist, what a rule's glob says — so no cell can drift from a
# description someone forgot to update. Behaviour is deliberately not described
# here: that was the hand-written half that kept being wrong, and a link to the
# file beats a paragraph about it.

KIT="${AGENTKIT_KIT:-../..}"
BLOB="https://github.com/developerinlondon/agentkit/blob/main"
OUT_UNITS=src/data/units.html
OUT_RULES=src/data/rules.html
OUT_ENV=src/data/kit.env

die() { echo "sync-kit-facts: $*" >&2; exit 1; }

[[ -d "$KIT/skills" && -d "$KIT/hooks/claude" ]] \
	|| die "kit not found at $KIT — pass AGENTKIT_KIT=/path/to/agentkit"
KIT=$(cd "$KIT" && pwd)

# A unit is a file named *-police. The only other files in these directories are
# a notification sound and the fail-closed supervisor, neither of which is one.
units_in() { find "$1" -maxdepth 1 -name "*-police$2" -type f 2>/dev/null | sed "s|.*/||; s|$2\$||" | sort; }

plugins=$(units_in "$KIT/plugins" .ts)
hooks=$(units_in "$KIT/hooks/claude" .sh)
policies=$(units_in "$KIT/policies/codex" .rules)
[[ -n "$plugins" && -n "$hooks" && -n "$policies" ]] || die "a surface directory came back empty"

# Codex runs one hook directly, so read that from the wiring rather than assume
# it from the file's location.
codex_hooks=$(grep -oE '[a-z-]+\.sh' "$KIT/hooks/codex/hooks.json" 2>/dev/null | sed 's/\.sh$//' | sort -u || true)
has() { grep -qxF "$2" <<<"$1"; }
join() { printf '%s\n' "$@" | awk '!seen[$0]++' | tr '\n' '\001' | sed 's/\x01$//; s/\x01/ · /g'; }

{
	echo "<!-- Generated by scripts/sync-kit-facts.sh — do not edit. -->"
	while read -r unit; do
		[[ -n "$unit" ]] || continue
		mech=() clients=() src=()
		if has "$plugins" "$unit"; then
			mech+=("plugin"); clients+=("OpenCode")
			src+=("<a href=\"$BLOB/plugins/$unit.ts\"><code>plugins/$unit.ts</code></a>")
		fi
		if has "$hooks" "$unit"; then
			mech+=("hook"); clients+=("Claude Code" "Grok")
			has "$codex_hooks" "$unit" && clients+=("Codex")
			src+=("<a href=\"$BLOB/hooks/claude/$unit.sh\"><code>hooks/claude/$unit.sh</code></a>")
		fi
		if has "$policies" "$unit"; then
			mech+=("policy"); clients+=("Codex")
			src+=("<a href=\"$BLOB/policies/codex/$unit.rules\"><code>policies/codex/$unit.rules</code></a>")
		fi
		printf '<tr><th class="m" scope="row">%s</th><td>%s</td><td>%s</td><td>%s</td></tr>\n' \
			"$unit" "$(join "${mech[@]}")" "$(join "${clients[@]}")" "$(join "${src[@]}")"
	done <<<"$(printf '%s\n%s\n%s\n' "$plugins" "$hooks" "$policies" | sort -u)"
} > "$OUT_UNITS"

# A rule's glob is printed as written; glossing it in prose is what drifts.
{
	echo "<!-- Generated by scripts/sync-kit-facts.sh — do not edit. -->"
	for f in "$KIT"/rules/*.md; do
		name=$(basename "$f" .md)
		glob=$(sed -n 's/^globs:[[:space:]]*//p' "$f" | head -1)
		[[ -n "$glob" ]] || die "rules/$name.md has no globs key"
		printf '<tr><th class="m" scope="row"><a href="%s/rules/%s.md">%s</a></th><td><code>%s</code></td></tr>\n' \
			"$BLOB" "$name" "$name" "$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' <<<"$glob")"
	done
} > "$OUT_RULES"

skills=$(find "$KIT/skills" -maxdepth 1 -mindepth 1 -type d | sed 's|.*/||' | sort)
total=$(wc -l <<<"$skills")
# Membership records are "<skill> <kit>"; "kit" and "explicit" are the
# other record types, never skill names.
membership=$(awk 'NF==2 && $1!~/^#/ && $1!="kit" && $1!="explicit"{print $1, $2}' "$KIT/skills/KITS" | sort)
product=$(awk '$2=="product"{print $1}' <<<"$membership")
review=$(awk '$2=="adversarial-review"{print $1}' <<<"$membership")
optin=$(awk '{print $1}' <<<"$membership")
# grep -c exits 1 on zero matches, which set -e turns into a silent death.
nproduct=$(grep -c . <<<"$product" || true)
nreview=$(grep -c . <<<"$review" || true)
ncore=$((total - nproduct - nreview))
[[ "$total" -gt 0 && "$nproduct" -gt 0 && "$nreview" -gt 0 && "$ncore" -gt 0 ]] \
	|| die "skill counts came back degenerate"

# Over the inputs actually read, so a reader can tell whether this snapshot still
# matches the kit it was taken from. The version is deliberately not here: it is
# a property of the build ref, not of this snapshot — a committed copy went five
# releases stale — so build.sh derives it from the tag at build time.
digest=$({ printf '%s\n' "$plugins" "$hooks" "$policies" "$skills" "$product"; cat "$KIT"/rules/*.md; } | sha256sum | cut -d' ' -f1)

{
	echo "# Generated by pages/site/sync-kit-facts.sh — do not edit."
	echo "KIT_SKILLS_TOTAL=$total"
	echo "KIT_SKILLS_CORE=$ncore"
	echo "KIT_SKILLS_PRODUCT=$nproduct"
	echo "KIT_SKILLS_REVIEW=$nreview"
	echo "KIT_UNITS_TOTAL=$(grep -c '^<tr>' "$OUT_UNITS")"
	echo "KIT_CORE_NAMES=\"$(comm -23 <(echo "$skills") <(echo "$optin") | tr '\n' ' ' | sed 's/ $//')\""
	echo "KIT_PRODUCT_NAMES=\"$(tr '\n' ' ' <<<"$product" | sed 's/ $//')\""
	echo "KIT_REVIEW_NAMES=\"$(tr '\n' ' ' <<<"$review" | sed 's/ $//')\""
	echo "KIT_DIGEST=$digest"
} > "$OUT_ENV"

echo "synced: $(grep -c '^<tr>' "$OUT_UNITS") units, $(grep -c '^<tr>' "$OUT_RULES") rules, $total skills ($ncore core, $nproduct product, $nreview review)"
echo "digest: $digest"
