export interface LockEntry {
  name: string;
  repo: string;
  ref: string;
  sha: string;
  pinned: string;
}

export const LOCK_FIELDS = ['name', 'repo', 'ref', 'commit', 'pinned-on'];

function header(reader: string): string[] {
  return [
    `# .agentkit/tastes.lock — the external taste sources this ${reader} reads, each pinned to`,
    '# the commit whose contents were reviewed. Regenerated by the taste skill; never hand-edited.',
    `# tab-separated, in the order brain.taste.sources declares: ${LOCK_FIELDS.join(', ')}`,
  ];
}

export function formatLock(entries: readonly LockEntry[], reader = 'repository'): string {
  const rows = entries.map((entry) =>
    [entry.name, entry.repo, entry.ref, entry.sha, entry.pinned].join('\t')
  );
  return `${[...header(reader), ...rows].join('\n')}\n`;
}

export function parseLock(text: string): LockEntry[] {
  const entries: LockEntry[] = [];
  for (const line of text.split('\n')) {
    if (line.trim() === '' || line.startsWith('#')) continue;
    const [name, repo, ref, sha, pinned] = line.split('\t');
    if (pinned === undefined) continue;
    entries.push({ name, repo, ref, sha, pinned } as LockEntry);
  }
  return entries;
}

// A pin's date says when this commit was reviewed, not when a command last ran:
// carrying it forward is what makes an unchanged re-sync an empty diff.
export function pinnedOn(
  entry: Omit<LockEntry, 'pinned'>,
  held: readonly LockEntry[],
  today: string,
): string {
  const previous = held.find((candidate) =>
    candidate.name === entry.name
    && candidate.repo === entry.repo
    && candidate.ref === entry.ref
    && candidate.sha === entry.sha
  );
  return previous?.pinned ?? today;
}
